# Generated by Django 6.0.1 on 2026-01-19 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('todo', '0001_initial'), ('todo', '0002_remove_task_fecha_de_creación_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En Progreso'), (2, 'Completado')], default=0, verbose_name='estado')),
                ('title', models.CharField(default='Title', max_length=200, verbose_name='titulo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
        ),
    ]
