# Generated by Django 6.0.1 on 2026-01-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripción', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('0', 'Pendiente'), ('1', 'En Progreso'), ('2', 'Completado')])),
                ('Fecha de creación', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
